# Generated by Django 3.2.9 on 2021-12-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('isBateauSauvetage', models.BooleanField(max_length=50)),
                ('type', models.CharField(choices=[('Voile', 'Voile'), ('Rame', 'Rame'), ('Moteur', 'Moteur')], max_length=50)),
                ('modele', models.CharField(choices=[('Canot', 'Canot'), ('Corvette de pilotage', 'Corvette de pilotage'), ('Remorqueur', 'Remorqueur'), ('Bateau-feu', 'Bateau-feu'), ('Goelette', 'Goelette'), ('Pneumatique', 'Pneumatique')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('titre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largeur', models.FloatField()),
                ('longueur', models.FloatField()),
                ('poids', models.FloatField()),
                ('tirantEau', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('legende', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Homme')], max_length=50)),
                ('dateNaissance', models.DateField()),
                ('dateDeces', models.DateField()),
                ('lieuNaissance', models.DateField()),
                ('lieuDeces', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temoignage', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BateauSauvetage',
            fields=[
                ('bateau_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.bateau')),
                ('affectation', models.CharField(max_length=100)),
                ('constructeur', models.CharField(max_length=100)),
                ('dateMiseEau', models.DateField()),
                ('essais', models.CharField(max_length=50)),
                ('finService', models.DateField()),
            ],
            bases=('webapp.bateau',),
        ),
        migrations.CreateModel(
            name='Victime',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.personne')),
                ('isEnfant', models.BooleanField()),
                ('isAdo', models.BooleanField()),
                ('isAlive', models.BooleanField()),
            ],
            bases=('webapp.personne',),
        ),
        migrations.CreateModel(
            name='Sauvetage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('sauvetageIndividuel', models.BooleanField()),
                ('personnes', models.ManyToManyField(to='webapp.Personne')),
                ('temoignages', models.ManyToManyField(to='webapp.Temoignage')),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='temoignage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.temoignage'),
        ),
        migrations.AddField(
            model_name='bateau',
            name='dimension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.dimension'),
        ),
        migrations.AddField(
            model_name='bateau',
            name='images',
            field=models.ManyToManyField(to='webapp.Image'),
        ),
        migrations.AddField(
            model_name='bateau',
            name='personnes',
            field=models.ManyToManyField(to='webapp.Personne'),
        ),
        migrations.AddField(
            model_name='bateau',
            name='sauvetages',
            field=models.ManyToManyField(to='webapp.Sauvetage'),
        ),
        migrations.CreateModel(
            name='Sauveteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.personne')),
                ('poste', models.CharField(max_length=50)),
                ('biographie', models.CharField(max_length=2000)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.decoration')),
                ('images', models.ManyToManyField(to='webapp.Image')),
            ],
            bases=('webapp.personne',),
        ),
    ]
