# Generated by Django 3.2.9 on 2021-12-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='lieuDeces',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lieuNaissance',
            field=models.CharField(max_length=50),
        ),
    ]
